# Generated by Django 4.2.16 on 2024-11-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('etc_note', models.TextField()),
                ('intr_rate', models.IntegerField(null=True)),
                ('intr_rate2', models.IntegerField(null=True)),
                ('intr_rate_type_nm', models.TextField()),
                ('save_trm', models.TextField()),
                ('rsrv_type_nm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('etc_note', models.TextField()),
                ('intr_rate', models.IntegerField(null=True)),
                ('intr_rate2', models.IntegerField(null=True)),
                ('intr_rate_type_nm', models.TextField()),
                ('save_trm', models.TextField()),
                ('rsrv_type_nm', models.TextField()),
            ],
        ),
    ]
